# Generated by Django 5.1.7 on 2025-03-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='cat/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('thumb_image', models.ImageField(null=True, upload_to='thumb_img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('fav', models.ManyToManyField(blank=True, related_name='favorite_videos', to='myapp.userreg')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to='myapp.userreg')),
            ],
            options={
                'ordering': ['category__name', 'title'],
            },
        ),
    ]
