# Generated by Django 5.1.6 on 2025-03-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_update_user_model'),
        ('myapp', '0004_rating'),
    ]

    operations = [
    ]
