# Generated by Django 5.1.6 on 2025-03-19 04:18

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_0002_update_user_model_0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='last_login',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
