# Generated by Django 5.0.2 on 2025-03-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userreg_options_alter_userreg_managers_and_more'),
    ]

    operations = [
    ]
